export const list = document.querySelector('#book-list')
export const form = document.querySelector('#add-book')
export const deleteButton = document.querySelector('#remove-book')
export const showModalButton = document.querySelector('#show-modal')
export const title = document.querySelector('#title')
export const author = document.querySelector('#author')
export const pages = document.querySelector('#pages')
